import { Nunito_Sans } from "next/font/google";
import ThemeToggle from "@/components/ThemeToggle";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "@/styles/globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunitoSans.className}>
        <ThemeProvider>
          <nav className="bg-card px-20 h-20 flex justify-between items-center shadow-lg">
            <h1 className="text-2xl font-extrabold">Where in the world?</h1>
            <ThemeToggle />
          </nav>
          <main className="px-20">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
