import { Nunito_Sans } from "next/font/google";
import ThemeToggle from "@/components/ThemeToggle";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "@/styles/globals.css";
import Link from "next/link";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

function Header() {
  return (
    <nav className="sticky top-0 z-50 bg-card shadow-lg">
      <div className="container mx-auto px-6 md:px-20 h-20 flex justify-between items-center">
        <Link href={"/"}>
          <h1 className="text-base md:text-2xl font-extrabold">
            Where in the world?
          </h1>
        </Link>
        <ThemeToggle />
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunitoSans.className}>
        <ThemeProvider>
          <Header />
          <main className="container mx-auto px-6 md:px-20">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
